apiVersion: v1
kind: Service
metadata:
  name: flask-prod-app-service
spec:
  type: NodePort
  selector:
    app: flask-prod-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
