name: Continuous Integration

on:
  pull_request:
    branches:
      - production

jobs:
  test-code-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
    
    - name: Run App Tests
      run: pytest

    - name: Building Image Test
      run: docker build -t ci:latest .
